- project:
    templates:
      - openstack-manuals-build-translation
      - openstack-manuals-jobs
    check:
      jobs:
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-linters
